### ISSUE TITLE
Stand up Team issues.

### ISSUE THREAD

**Issue by mesielepush** [leonmezu1/Bot-Capstone#1]
1.- Rspec should be used from the beginning, even when all test will naturally fail, that is the point of TDD.
2.- Captions for testing should always be different, so you can see clearly which tests passes and which ones don't.

Other than that pretty good Leonard.

**Comment by leonmezu1** [comment]
Rspec is now enabled and all the test cases proposed are working as expected.

Thanks, team!

🦾🔥
